<?php

/**
 * Provide a admin area view for the plugin
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 *
 * @link       https://www.keishaperry.com/
 * @since      1.0.0
 *
 * @package    Toh_Json
 * @subpackage Toh_Json/admin/partials
 */
?>

<!-- This file should primarily consist of HTML with a little bit of PHP. -->
<!-- UIkit CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.25/css/uikit.min.css" />

<!-- UIkit JS -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.25/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.25/js/uikit-icons.min.js"></script> -->

<div class="uk-container-expand">


<!--     <div class="js-upload uk-placeholder uk-text-center uk-padding-large uk-margin-large">
        <span uk-icon="icon: cloud-upload"></span>
        <span class="uk-text-middle">Import KML & JSON data into temp store by dropping a file here or</span>
        <div uk-form-custom>
            <input id="TOHfiles" type="file" name="files[]" multiple>
            <span class="uk-link">selecting one</span>
        </div>
    </div> 
    <div id="genJsonKML" class=" uk-margin-large-bottom uk-width-1-1 ">
                <form class="uk-width-1-1 uk-flex" >
                    <input name="test" val="test value" type="hidden" />
                    <textarea id="memoryJson" name="json" class="uk-hidden"></textarea>
                    <button id="genJson" type="button" class="uk-hidden uk-margin-auto uk-primary uk-button-large uk-width-1-3 special-btn"
                        style="">STORE TEMP JSON</button>
                </form>
            </div>
    <div>
                <table id="memoryTable" class="uk-table uk-table-divider uk-table-hover uk-table-responsive">
                    <thead>
                        <tr>
                            <th class="">sCode</th>
                            <th class="">sCategory</th>
                            <th class="">sName</th>
                            <th class="">sAddress</th>
                            <th class="">sCity</th>
                            <th class="">sState</th>
                            <th class="">sGPS</th>
                            <th class="">sAccess</th>
                            <th class="">sFlavor</th>
                            <th class="">sMadeInAmerica</th>
                            <th class="">sImageName</th>
                            <th class="">sTrophyGroup</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr id="rowStub" class="uk-hidden">
                            <td data-key="bonusCode"></td>
                            <td data-key="category"></td>
                            <td data-key="name"></td>
                            <td data-key="address"></td>
                            <td data-key="city"></td>
                            <td data-key="state"></td>
                            <td data-key="GPS"></td>
                            <td data-key="Access"></td>
                            <td data-key="flavor"></td>
                            <td data-key="madeinamerica"></td>
                            <td data-key="imageName"></td>
                            <td data-key="sTrophyGroup"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
</div>
    -->

<div class="uk-container uk-padding-large">
<form id="scrapeBuilderForm" class="uk-width-1-1 uk-grid uk-grid-large" uk-grid uk-height-match action="<?php echo admin_url( 'admin-post.php' ); ?>">
    <div class="uk-margin">
    <?php if (current_user_can('administrator')) :?>
    <?php $next_version = $this->get_next_version(); ?>
        <div class="uk-margin">
            <input type="text" disabled readonly value="<?php echo $next_version; ?>"/>
        </div>
    <?php endif; ?>
    </div>
    <div class="uk-margin uk-margin-top-large">
            <input type="hidden" name="action" value="create_json_record">
        <button type="submit" id="add-scrape" class="uk-button uk-button-large uk-button-secondary">Generate JSON cache</button>
    </div>
</form>
<?php $json_records = $this->get_bonus_json_records(); ?>
<table class="uk-container uk-table uk-table-divider">
    <thead>
        <tr>
            <th>Version</th>
            <th>Generated on</th>
            <th>Generated by</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
<?php foreach($json_records as $record) : ?>
<tr>
    <th><?php echo $record->version; ?></th>
    <th><?php 
    $date = new DateTime($record->created_at);
    echo $date->format('m-d-Y'); ?></th>
    <th><?php $user = get_user_by("id",$record->created_by);echo $user->first_name; ?></th>
    <th><a href="<?php echo site_url("/wp-json/toh/v1/bonus-data?v=".$record->version);?>">File view</a></th>
    <th><a class="uk-link-reset" title="doesn't work yet..." href="">File download</a></th>
</tr>
<?php endforeach; ?>

    </tbody>
    
</table>



<form class="uk-width-1-1 uk-margin" action="<?php echo admin_url( 'admin-post.php' ); ?>">
    <input type="hidden" name="action" value="trigger_scrape">
    <?php submit_button( 'Scrape live data' ); ?>
</form>
<p uk-margin>
    <form class="uk-width-1-1 uk-margin" action="<?php echo admin_url( 'admin-post.php' ); ?>">
        <input type="hidden" name="action" value="trigger_scrape_db">
        <input type="hidden" name="db_tablename" value="dogs">
        <button type="submit" class="uk-button uk-button-default uk-button-large">Import War Dogs DB</button>
    </form>
    <form class="uk-width-1-1 uk-margin" action="<?php echo admin_url( 'admin-post.php' ); ?>">
        <input type="hidden" name="action" value="trigger_scrape_db">
        <input type="hidden" name="db_tablename" value="doughboys">
        <button type="submit" class="uk-button uk-button-default uk-button-large">Import Doughboys DB</button>
    </form>
    <form class="uk-width-1-1 uk-margin" action="<?php echo admin_url( 'admin-post.php' ); ?>">
        <input type="hidden" name="action" value="trigger_scrape_db">
        <input type="hidden" name="db_tablename" value="goldstars">
        <button type="submit" class="uk-button uk-button-default uk-button-large">Import Gold Stars DB</button>
    </form>
    <form class="uk-width-1-1 uk-margin" action="<?php echo admin_url( 'admin-post.php' ); ?>">
        <input type="hidden" name="action" value="trigger_scrape_db">
        <input type="hidden" name="db_tablename" value="hueys">
        <button type="submit" class="uk-button uk-button-default uk-button-large">Import Hueys DB</button>
    </form>
    <form class="uk-width-1-1 uk-margin" action="<?php echo admin_url( 'admin-post.php' ); ?>">
        <input type="hidden" name="action" value="trigger_scrape_db">
        <input type="hidden" name="db_tablename" value="parks">
        <button type="submit" class="uk-button uk-button-default uk-button-large">Import Parks DB</button>
    </form>
</p>
<p uk-margin>
    <form class="uk-width-1-1 uk-margin" action="<?php echo admin_url( 'admin-post.php' ); ?>">
        <input type="hidden" name="action" value="trigger_purge_db">
        <button type="submit" class="uk-button uk-button-default uk-button-large">Purge SQL DB Bonuses</button>
    </form>
</p>
</div>
